image: node:12.14.0

stages:
  - build
  - release
  - upload
  - sonarqube-check

before_script:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/config
  - chmod 700 ~/.ssh/id_rsa
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - echo "$SSH_CONFIG" > ~/.ssh/config
  - echo "140.82.112.3 github.com" >> /etc/hosts
  - |
    if [ `grep -c "npmjs" yarn.lock` -ne '0' ];then
      echo 不许使用 npmjs.org 的依赖，太卡，检查 yarn.lock;
      exit 1;
    fi
  - |
    if [ `grep -c "cnpm" yarn.lock` -ne '0' ];then
      echo 不许使用 cnpm 的依赖，太卡，检查 yarn.lock;
      exit 1;
    fi
  - |
    if [ `grep -c "yarnpkg.com" yarn.lock` -ne '0' ];then
      echo 不许使用 yarnpkg.com 的依赖，太卡，检查 yarn.lock;
      exit 1;
    fi
  - |
    case "$CI_COMMIT_REF_NAME" in
      "master")
        #echo $(sh ./increment_version.sh) > version.txt
        export VERSION=$(cat version.txt)
        OSS_URL=${OSS_PROD}
        ;;
      *)
        export VERSION=$(cat version.txt)-${CI_COMMIT_SHORT_SHA}
        OSS_URL=${OSS_DAILY}
        ;;
    esac

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_TAG =~ "/^$/"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_COMMIT_TAG =~ "/^$/"'
      when: on_success
  image: docker:latest
  script:
    - docker build -t authing-wechat-official-account:${VERSION} .
    - mkdir docker-image
    - docker save -o docker-image/${CI_PROJECT_NAME}-${VERSION}-docker.tar authing-wechat-official-account:${VERSION}
  artifacts:
    untracked: false
    paths:
      - docker-image
    expire_in: 3 days

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_COMMIT_TAG =~ "/^$/"'
  script:
    - echo $CI_COMMIT_REF_NAME
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git tag -a ${VERSION} -m "${VERSION}"
    - git push git@git.authing.co:authing-next/authing-wechat-official-account.git --tags
  artifacts:
    untracked: false
    paths:
      - build
    expire_in: 30 days
  dependencies:
    - build

# upload:oss:
#   stage: upload
#   rules:
#     - if: '$CI_COMMIT_TAG =~ "/^$/"'
#   image:
#     name: fuergaosi/ossutil:latest
#   script:
#     - >
#       ossutil --access-key-id ${ALIYUN_ACCESS_KEY}
#       --access-key-secret ${ALIYUN_ACCESS_KEY_SECRET}
#       -e oss-cn-beijing.aliyuncs.com cp -r docker-image oss://${OSS_URL}/authing-wechat-official-account/${VERSION}/docker
#   dependencies:
#     - build

upload:docker:
  stage: upload
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/"'
  image: docker:latest
  script:
    - docker load < docker-image/${CI_PROJECT_NAME}-${VERSION}-docker.tar
    - docker login -u ${DOCKER_USERNAME}  -p ${DOCKER_PASSWD}  ${DOCKER_REPO}
    - export IMAGE_NAME=${DOCKER_REPO}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
    - docker tag authing-wechat-official-account:${VERSION} ${IMAGE_NAME}:${VERSION}
    - docker push ${IMAGE_NAME}:${VERSION}
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest;
        docker push ${IMAGE_NAME}:latest;
      fi
  dependencies:
    - build

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - master
